### ISSUE TITLE
Configure persistent timeout and netmask 

### ISSUE THREAD

**Issue by tydice** [mqliang/goipvs#10]
First of all, I love your codes and thank you for what you've done.

I've tried to set persistent flag of virtual service, which is -p or --persistent [timeout] in ipvsadm, but I couldn't do that.
Maybe I'm doing wrong but I can't find any documents or comments about it.

I tested with those codes :
```
      	h, _ := libipvs.New()

	svc = libipvs.Service{
		Address:       net.ParseIP("172.0.0.1"),
		AddressFamily: syscall.AF_INET,
		Protocol:      libipvs.Protocol(syscall.IPPROTO_TCP),
		Port:          80,
		
                Timeout:       100,
		Netmask:       32,

		SchedName: libipvs.LeastConnection,
	}

 	if err = h.NewService(&svc); err != nil {
		panic(err)
	}
```

Even though I specify either timeout or netmask, persistent flag are never set in ipvs.

**Comment by mqliang** [comment]
@DoHyeongPark Hi, maybe you can take a look at this lib: https://github.com/docker/libnetwork/tree/master/ipvs

which is maintained by docker libnetwork team
