### ISSUE TITLE
Getting error: genl hub loop exit 

### ISSUE THREAD

**Issue by amitgurav04** [mqliang/goipvs#16]
I am creating ipvs handle using

handle, err := libipvs.New()

Then I am listing services:

services, err := handle.ListServices()

After some time this gives an error: genl hub loop exit 

And goes into waiting state.

Please help me to fix this. Thanks in advance.

**Comment by mqliang** [comment]
Hey, you can take a look at this lib: https://github.com/docker/libnetwork/tree/master/ipvs

which is maintained by docker libnetwork team
