### ISSUE TITLE
修改activeconn

### ISSUE THREAD

**Issue by mynicolas** [mqliang/goipvs#17]
当我用UpdateDestination方法修改ActiveConns 时，没有产生任何效果，这个值不能修改吗？

**Comment by mqliang** [comment]
Hey, suggest you to change to https://github.com/moby/ipvs, which have a better community support

**Comment by mqliang** [comment]
A pointer of how to use  Service/Endpoint of https://github.com/moby/ipvs:
- https://github.com/moby/libnetwork/blob/master/service_linux.go
- https://github.com/moby/libnetwork/blob/master/endpoint.go

Hope this is helpful.
